version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/waterlevels
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local