default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: waterlevels_development
test:
  <<: *default
  database: waterlevels_test
production:
  <<: *default
  database: waterlevels_production
