# encoding: UTF-8
CSV_URL: 'http://www.capetown.gov.za/_layouts/OpenDataPortalHandler/DownloadHandler.ashx?DocumentName=Dam+levels+update+2012-2017.csv&DatasetDocument=http%3a%2f%2fcityapps.capetown.gov.za%2fsites%2fopendatacatalog%2fDocuments%2fDam+levels%2fDam+levels+update+2012-2017.csv'
DAMS: 'WEMMERSHOEK|STEENBRAS LOWER|STEENBRAS UPPER|VOËLVLEI|THEEWATERSKLOOF|BERG RIVER'
